const ActionTypes = {
    SET_FOLDERS: 'setFolders',
    ADD_FOLDER: 'addFolder',
    SET_SELECTED_FOLDER: 'setSelectedFolder',
    ADD_SELECTED_FOLDER_DECK: 'addSelectedFolderDeck',
    DELETE_SELECTED_FOLDER_DECK: 'deleteSelectedFolderDeck',
    DELETE_SELECTED_FOLDER: 'deleteSelectedFolder',
    SET_AVALIABLE_DECKS: 'setAvaliableDecks',
    SET_AN_AVALIABLE_DECK: 'setAnAvaliableDeck',
    SET_DECKS: 'setDecks',
    ADD_DECK: 'addDeck',
    SET_SELECTED_DECK: 'setSelectedDeck',
    DELETE_SELECTED_DECK: 'deleteselectedDeck',
    SET_CURRENT_CARD_INDEX: 'setCurrentCardIndex',
    DELETE_CARD_FROM_SELECTED_DECK: 'deleteCardFromSelectedDeck',
    SET_CARD_FROM_SELECTED_DECK: 'setCardFromSelectedDeck',
    SET_EDIT_DECK: 'setEditDeck',
    SET_EDIT_DECK_NAME: 'setEditDeckName',
    SET_EDIT_DECK_DESCRIPTION: 'setEditDeckDescription',
    SET_EDIT_DECK_FOLDER_ID: 'setEditDeckFolderId',
    SET_EDIT_DECK_CARDS: 'setEditDeckCards',
    ADD_EDIT_DECK_CARD: 'addEditDeckCard',
    SET_EDIT_DECK_CARD_FRONT: 'setEditDeckCardFront',
    SET_EDIT_DECK_CARD_BACK: 'setEditDeckCardBack',
    DELETE_EDIT_DECK_CARD: 'delete  tDeckCard',
    CLEAR_EDIT_DECK: 'clearEditDeck',
};

export default ActionTypes;